services:
  - type: worker
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u bot_multi_admin_persistent.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_MAP
        sync: false
      - key: DB_PATH
        value: /var/data/bot_data.sqlite3
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
